// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(HistoricalMapDbContext))]
    [Migration("20260630030701_RefactorToTPC")]
    partial class RefactorToTPC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataTypes.Entities.OsmNode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangesetId")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("OsmNode", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DataTypes.Entities.OsmRelation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangesetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OsmRelation", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DataTypes.Entities.OsmTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OsmRelationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OsmWayId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("OsmNodeId");

                    b.HasIndex("OsmRelationId");

                    b.HasIndex("OsmWayId");

                    b.HasIndex("EntityId", "EntityType");

                    b.HasIndex("Key", "Value");

                    b.ToTable("OsmTags");
                });

            modelBuilder.Entity("DataTypes.Entities.OsmWay", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ChangesetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OsmWay", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DataTypes.Entities.RelationMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OsmWayId")
                        .HasColumnType("bigint");

                    b.Property<long>("RelationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("OsmNodeId");

                    b.HasIndex("OsmWayId");

                    b.HasIndex("RelationId");

                    b.HasIndex("MemberId", "MemberType");

                    b.HasIndex("RelationId", "SequenceNumber");

                    b.ToTable("RelationMembers");
                });

            modelBuilder.Entity("DataTypes.Entities.WayNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<long>("WayId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("WayId");

                    b.HasIndex("WayId", "SequenceNumber");

                    b.ToTable("WayNodes");
                });

            modelBuilder.Entity("DataTypes.Entities.OsmTag", b =>
                {
                    b.HasOne("DataTypes.Entities.OsmNode", null)
                        .WithMany("Tags")
                        .HasForeignKey("OsmNodeId");

                    b.HasOne("DataTypes.Entities.OsmRelation", null)
                        .WithMany("Tags")
                        .HasForeignKey("OsmRelationId");

                    b.HasOne("DataTypes.Entities.OsmWay", null)
                        .WithMany("Tags")
                        .HasForeignKey("OsmWayId");
                });

            modelBuilder.Entity("DataTypes.Entities.RelationMember", b =>
                {
                    b.HasOne("DataTypes.Entities.OsmNode", null)
                        .WithMany("RelationMembers")
                        .HasForeignKey("OsmNodeId");

                    b.HasOne("DataTypes.Entities.OsmWay", null)
                        .WithMany("RelationMembers")
                        .HasForeignKey("OsmWayId");

                    b.HasOne("DataTypes.Entities.OsmRelation", "Relation")
                        .WithMany("Members")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("DataTypes.Entities.WayNode", b =>
                {
                    b.HasOne("DataTypes.Entities.OsmNode", "Node")
                        .WithMany("WayNodes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataTypes.Entities.OsmWay", "Way")
                        .WithMany("WayNodes")
                        .HasForeignKey("WayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Way");
                });

            modelBuilder.Entity("DataTypes.Entities.OsmNode", b =>
                {
                    b.Navigation("RelationMembers");

                    b.Navigation("Tags");

                    b.Navigation("WayNodes");
                });

            modelBuilder.Entity("DataTypes.Entities.OsmRelation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DataTypes.Entities.OsmWay", b =>
                {
                    b.Navigation("RelationMembers");

                    b.Navigation("Tags");

                    b.Navigation("WayNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
